using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using Kurs7PM.Kurs7DataSetTableAdapters;


namespace Kurs7PM.Клиент
{
    /// <summary>
    /// Логика взаимодействия для Store.xaml
    /// </summary>
    public partial class Store : Window
    {
       Kurs7DataSet DataSet = new Kurs7DataSet();
       medicationTableAdapter MTA = new medicationTableAdapter();

        public Store()
        {
            InitializeComponent();
            data.ItemsSource = DataSet.medication.DefaultView;
            MTA.Fill(DataSet.medication);
            data.SelectedIndex = -1;
        }

        private void Dob_korz(object sender, RoutedEventArgs e)
        {
            Button button = sender as Button;
            int index = Int32.Parse(button.Tag.ToString());
            index++;
            MessageBox.Show(index.ToString() );
        }

        //Отправляет корзину в конец datagrid
        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var grid = (DataGrid)sender;
            foreach (var item in grid.Columns)
            {
                if (item.Header.ToString() == "Корзина")
                {
                    item.DisplayIndex = grid.Columns.Count - 1;
                    break;
                }
            }
        }

        //Убирает первый столбец id
        private void DataGrid_OnAutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (e.PropertyName == "ID_medication")
            {
                e.Cancel = true;
            }
        }
    }
}
