using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using Kurs7PM.Kurs7DataSetTableAdapters;


namespace Kurs7PM.Клиент
{
    /// <summary>
    /// Логика взаимодействия для Store.xaml
    /// </summary>
    public partial class Store : Window
    {
        Kurs7DataSet DataSet = new Kurs7DataSet();
        medicationTableAdapter MTA = new medicationTableAdapter();
        ShoppingCartTableAdapter STA = new ShoppingCartTableAdapter();
        ShoppingCartHelpTableAdapter SHTA = new ShoppingCartHelpTableAdapter();

        public Store()
        {
            InitializeComponent();
            data.ItemsSource = DataSet.medication.DefaultView;
            MTA.Fill(DataSet.medication);
            STA.Fill(DataSet.ShoppingCart);
        }

        private void Dob_korz(object sender, RoutedEventArgs e)
        {
            Button button = sender as Button;
            int index = Int32.Parse(button.Tag.ToString());
            MessageBox.Show(index.ToString() );


            string Sql = "select * from dbo.medication";
            SqlConnection connection = new SqlConnection("Data Source=DESKTOP-1KN5R8D;Initial Catalog=Kurs7;Integrated Security=True");
            connection.Open();
            SqlCommand command = new SqlCommand(Sql, connection);
            SqlDataReader reader = command.ExecuteReader();
            List<string> names = new List<string>();
            List<string> price = new List<string>();
            while (reader.Read())
            {
                names.Add(reader["Name_medication"].ToString());
                price.Add(reader["Price"].ToString());
            }
            reader.Close();
            connection.Close();

            int PriceInt = Int32.Parse(price[index]);
            STA.InsertQuery(names[index], 1, PriceInt);
            SHTA.InsertQuery(PriceInt);

        }

        private void korzina(object sender, RoutedEventArgs e)
        {
            ShoppingCart go = new ShoppingCart();
            go.Show();
            this.Close();
        }

        //Отправляет корзину в конец datagrid
        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var grid = (DataGrid)sender;
            foreach (var item in grid.Columns)
            {
                if (item.Header.ToString() == "Корзина")
                {
                    item.DisplayIndex = grid.Columns.Count - 1;
                    break;
                }
            }
        }

        //Убирает первый столбец id
        private void DataGrid_OnAutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (e.PropertyName == "ID_medication")
            {
                e.Cancel = true;
            }
        }
    }
}
