using Kurs7PM.Kurs7DataSetTableAdapters;
using Kurs7PM.Администратор;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace Kurs7PM.Авторизация.Регистрация
{
    public partial class Sklad : Window
    {
        Kurs7DataSet DataSet = new Kurs7DataSet();
        SkladTableAdapter STA = new SkladTableAdapter();
        string Kurs7ConnectionString = Properties.Settings.Default.Kurs7ConnectionString1;

        public Sklad()
        {
            InitializeComponent();
            STA.Fill(DataSet.Sklad);
        }

        //Удаляет запись выбранной ячейки
        private void minus_korz(object sender, RoutedEventArgs e)
        {
            Button button = sender as Button;
            int index = Int32.Parse(button.Tag.ToString());
            int id = index + 1;

            string Sql = "select * from dbo.sklad";
            SqlConnection connection = new SqlConnection(Kurs7ConnectionString);
            connection.Open();
            SqlCommand command = new SqlCommand(Sql, connection);
            SqlDataReader reader = command.ExecuteReader();
            List<string> name = new List<string>();
            while (reader.Read())
            {
                name.Add(reader["Название"].ToString());
            }
            reader.Close();
            connection.Close();

            string Sql1 = "DROP TABLE " + name[index];
            SqlConnection connection1 = new SqlConnection(Kurs7ConnectionString);
            connection1.Open();
            SqlCommand command1 = new SqlCommand(Sql1, connection1);
            SqlDataReader reader1 = command1.ExecuteReader();
            reader1.Close();
            connection1.Close();

            STA.DeleteQuery(id);
            STA.Fill(DataSet.Sklad);
        }

        //Отправляет удаление в конец datagrid
        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var grid = (DataGrid)sender;
            foreach (var item in grid.Columns)
            {
                if (item.Header.ToString() == "Удалить")
                {
                    item.DisplayIndex = grid.Columns.Count - 1;
                    break;
                }
            }
        }

        //Убирает первый столбец datagrid (id)
        private void DataGrid_OnAutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (e.PropertyName == "ID_sklad")
            {
                e.Cancel = true;
            }
        }

        //Позволяет перетаскивать окно
        private void StackPanel_MouseDown(object sender, MouseButtonEventArgs e)
        {
            if (e.ChangedButton == MouseButton.Left)
            {
                this.DragMove();
            }
        }

        //Работа кнопки выключения программы
        private void Exit_with_application(object sender, RoutedEventArgs e)
        {
            System.Windows.Application.Current.Shutdown();
        }

        //Работа кнопки разворачивания программы
        private void Maximized_with_application(object sender, RoutedEventArgs e)
        {
            if (this.WindowState == WindowState.Normal)
            {
                this.WindowState = WindowState.Maximized;
            }
            else { this.WindowState = WindowState.Normal; }
        }

        //Работа кнопки сворачивания программы
        private void Minimazed_with_application(object sender, RoutedEventArgs e)
        {
            this.WindowState = WindowState.Minimized;
        }

        //Добавление
        private void add_branch(object sender, RoutedEventArgs e)
        {
            STA.InsertQuery(filials.Text);
            STA.Fill(DataSet.Sklad);

            string priem = filials.Text;
            string Sql = "CREATE TABLE " + priem + "(\tID_providersklad int identity(1,1) primary key,\r\n\tНазвание nvarchar(50) NOT NULL,\r\n\tКоличество int  NOT NULL,\r\n\tЦена int  NOT NULL);";
            SqlConnection connection = new SqlConnection(Kurs7ConnectionString);
            connection.Open();
            SqlCommand command = new SqlCommand(Sql, connection);
            SqlDataReader reader = command.ExecuteReader();
            reader.Close();
            connection.Close();

            MessageBox.Show("Вы успешно создали склад!");
            Авторизация.Регистрация.Provider go = new Авторизация.Регистрация.Provider(priem);
            go.Show();
            Close();
        }

        //Переход
        private void reg(object sender, RoutedEventArgs e)
        {
           Авторизация.Регистрация.Provider go = new Авторизация.Регистрация.Provider("");
            go.Show();
            Close();
        }
    }
}
