using Kurs7PM.Авторизация;
using Kurs7PM.Клиент;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using Kurs7PM.Kurs7DataSetTableAdapters;
using Kurs7PM.Авторизация.Регистрация;

namespace Kurs7PM.Поставщик
{
    /// <summary>
    /// Логика взаимодействия для Provider.xaml
    /// </summary>
    public partial class Provider : Window
    {
        Kurs7DataSet DataSet = new Kurs7DataSet();
        SkladTableAdapter STA = new SkladTableAdapter();
        string Kurs7ConnectionString = Properties.Settings.Default.Kurs7ConnectionString1;

        string allsklad;
        public Provider(string skklad)
        {
            InitializeComponent();

            string Sql = "select * from " + skklad;
            SqlConnection connection = new SqlConnection(Kurs7ConnectionString);
            connection.Open();
            SqlDataAdapter command = new SqlDataAdapter(Sql, connection);
            DataSet ds = new DataSet();
            command.Fill(ds, skklad);
            connection.Close();

            data.ItemsSource = ds.Tables[skklad].DefaultView; ;

            allsklad = skklad;
            addressap.Text = skklad;
        }

        //Удаляет запись выбранной ячейки
        private void minus_korz(object sender, RoutedEventArgs e)
        {
            Button button = sender as Button;
            int index = Int32.Parse(button.Tag.ToString());
            int id = index + 1;

            string Sql = "DELETE  FROM " + allsklad + " WHERE ID_providersklad=" + id;
            SqlConnection connection = new SqlConnection(Kurs7ConnectionString);
            connection.Open();
            SqlCommand command = new SqlCommand(Sql, connection);
            SqlDataReader reader = command.ExecuteReader();
            reader.Close();
            connection.Close();

            string Sql1 = "select * from " + allsklad;
            SqlConnection connection1 = new SqlConnection(Kurs7ConnectionString);
            connection1.Open();
            SqlDataAdapter command1 = new SqlDataAdapter(Sql1, connection1);
            DataSet ds1 = new DataSet();
            command1.Fill(ds1, allsklad);
            connection1.Close();

            data.ItemsSource = ds1.Tables[allsklad].DefaultView; ;

        }

        //Отправляет удаление в конец datagrid
        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var grid = (DataGrid)sender;
            foreach (var item in grid.Columns)
            {
                if (item.Header.ToString() == "Удалить")
                {
                    item.DisplayIndex = grid.Columns.Count - 1;
                    break;
                }
            }
        }

        //Переход к окну авторизации
        private void authorization(object sender, RoutedEventArgs e)
        {
            MainWindow go = new MainWindow();
            go.Show();
            Close();
        }

        //Убирает первый столбец id
        private void DataGrid_OnAutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (e.PropertyName == "ID_providersklad")
            {
                e.Cancel = true;
            }
        }

        //Позволяет перетаскивать окно
        private void StackPanel_MouseDown(object sender, MouseButtonEventArgs e)
        {
            if (e.ChangedButton == MouseButton.Left)
            {
                this.DragMove();
            }
        }

        //Работа кнопки выключения программы
        private void Exit_with_application(object sender, RoutedEventArgs e)
        {
            System.Windows.Application.Current.Shutdown();
        }

        //Работа кнопки разворачивания программы
        private void Maximized_with_application(object sender, RoutedEventArgs e)
        {
            if (this.WindowState == WindowState.Normal)
            {
                this.WindowState = WindowState.Maximized;
            }
            else { this.WindowState = WindowState.Normal; }
        }

        //Работа кнопки сворачивания программы
        private void Minimazed_with_application(object sender, RoutedEventArgs e)
        {
            this.WindowState = WindowState.Minimized;
        }


        private void add_sklad(object sender, RoutedEventArgs e)
        {
            string Sql = "INSERT INTO " + allsklad + " (Название, Количество, Цена)" + " VALUES (" + "'" +name.Text + "'" + ", " + quantity.Text + ", " + price.Text + ");";
            SqlConnection connection = new SqlConnection(Kurs7ConnectionString);
            connection.Open();
            SqlCommand command = new SqlCommand();
            command.CommandText = Sql;
            command.Connection= connection;
            command.ExecuteNonQuery();
            connection.Close();

            string Sql1 = "select * from " + allsklad;
            SqlConnection connection1 = new SqlConnection(Kurs7ConnectionString);
            connection1.Open();
            SqlDataAdapter command1 = new SqlDataAdapter(Sql1, connection1);
            DataSet ds1 = new DataSet();
            command1.Fill(ds1, allsklad);
            connection1.Close();

            data.ItemsSource = ds1.Tables[allsklad].DefaultView; ;
        }
    }
}
